name: CI Pipeline for Maven

on:
  push:
    branches: 
        - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps: 
      - name: repository
        uses: actions/checkout@v4

      - name: Java Setup
        uses: actions/setup-java@v4

      - name: dependencies
        run: mvn dependency:resolve

      - name: compile and run tests
        run: mvn clean test package

      - name: generate artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build artifacts
          path: |
                target-*.jar
                target-*.war
